### PR TITLE
I7 par val

### LINKED ISSUE #7: Parameter values are not updating when a layer is changed in the ‘Parameter Viewer’.
Description:
- I’m creating a simple model with the following layers: Input → Linear_1 → Linear_2 → MSE. However, when I set the parameters for ‘Linear_1’ to (1, 128) and then click on ‘Linear_2’, the ‘Parameter Viewer’ still displays the old values from ‘Linear_1’

Reproduction Steps:
1. Create a blank project
2. Design Following Model: Input → Linear_1 → Linear_2 → MSE
3. Set parameter (128,1) for 'Linear_1'
4. Click on 'Layer_2'
5. Observe 'Prameter Viewer'

OS:
MacOs 14.5

### PR DESCRIPTION
**Pull request by Jaimin020**

### CODE REVIEW

File: src/frontend/utils/graphUtils/GraphDataManager.ts [hunk 1]
```diff
@@ -39,6 +39,13 @@ export class GraphDataManager {
     return this.hyperparameters;
   }
 
+  clearAllNodesAndEdges() {
```
Comment (yashjain7856) [inline src/frontend/utils/graphUtils/GraphDataManager.ts:42]: we can provide this as a separate button as well, to clear the canvas.
this should also be triggered when the user opens a new model

**Review by yashjain7856 — APPROVED** [review]

File: src/frontend/utils/graphUtils/GraphDataManager.ts (hunk 1 above)
Comment (Jaimin020) [reply src/frontend/utils/graphUtils/GraphDataManager.ts:42]: Yes, that makes sense. I’ll initiate the implementation through a new issue.
